Algoritmo "Cambio de moedas"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 04/09/2023
Var
// Seção de Declarações das variáveis 
     reais, dolar, euro : real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   Escreval ("quantos reais tem: ")
   Leia(reais)
   
   dolar<- reais/5,32
   euro <- reais/6,10

   Escreval("Posso ter: U$$ ",dolar," dolares")
   Escreval("Posso ter: $ ", euro," euros")

Fimalgoritmo