Algoritmo "Conversor de ºF para ºC"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 04/09/2023
Var
// Seção de Declarações das variáveis 
   F , C : Real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   Escreval ("Qual a temperatura em Fareheigt: ")
   Leia(F)

   C <- (F-32)/1.8
   
   Escreval("Em Celcios seria: ", C:4:1)

Fimalgoritmo